### ISSUE TITLE
Spaces around stuff

### ISSUE THREAD

**Issue by janhancic** [caplin/StyleGuide#2]
We probably need to define where people should put spaces around () and stuff like that.

For instance: if(something) {} vs if ( something ){} ...

**Comment by kybernetikos** [comment]
mmmm
I don't feel very strongly.

I lean towards spaces after keywords, spaces around operators except unary operators and no spaces after  ( or before ), but a space between ) and {

**Comment by janhancic** [comment]
That was just an example of what I'm on about. I just think we need to write the rules down and then discuss them.

**Comment by janhancic** [comment]
Have a look at my first draft here: https://github.com/janhancic/StyleGuide/blob/gh-pages/readme.md#spaces and tell me what you think.

**Comment by janhancic** [comment]
Once we agree on this (well, at least the two of us), I'll update your examples to follow this ...
